//
// Created by Dustin Burda on 11/19/23.
//

#ifndef RASTERIZATIONENGINE_BOUNDINGBOX_H
#define RASTERIZATIONENGINE_BOUNDINGBOX_H

class Box {
private:

};

#endif //RASTERIZATIONENGINE_BOUNDINGBOX_H
